/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InicioMenuPrincipal;

import conteoVotos.Conteo;
import GestionElecciones.CrearEleccion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BtnEleccion = new javax.swing.JButton();
        BtnMesa = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        BtnActa = new javax.swing.JButton();
        BtnVotar = new javax.swing.JButton();
        BtnConteo = new javax.swing.JButton();
        BtnCerra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel2.setText("MENÚ PRINCIPAL");

        BtnEleccion.setText("Elecciones");
        BtnEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEleccionActionPerformed(evt);
            }
        });

        BtnMesa.setText("Mesas electorales");
        BtnMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMesaActionPerformed(evt);
            }
        });

        BtnRegistro.setText("Registro de votos");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        BtnActa.setText("Actas electorales");
        BtnActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActaActionPerformed(evt);
            }
        });

        BtnVotar.setText("Votar ya!");
        BtnVotar.setActionCommand("Votar");
        BtnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVotarActionPerformed(evt);
            }
        });

        BtnConteo.setText("Conteo de votos");
        BtnConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConteoActionPerformed(evt);
            }
        });

        BtnCerra.setText("Cerrar sesión");
        BtnCerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(BtnCerra)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegistro)
                    .addComponent(BtnEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnActa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMesa))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConteo))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCerra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnConteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnActa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEleccionActionPerformed
            String user = Usuario.getRol();
            if("member".equals(user)){
                JOptionPane.showMessageDialog(this, "No tienes acceso a esta opción", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                CrearEleccion elec = new CrearEleccion();
                elec.setVisible(true); // Mostrar la nueva ventana
                this.dispose();
            }
    }//GEN-LAST:event_BtnEleccionActionPerformed
    
    private void BtnMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMesaActionPerformed
        // TODO add your handling code here:
        mesaElectoral.MesaVotacion mesa = new mesaElectoral.MesaVotacion();
        mesa.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnMesaActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        String user = Usuario.getRol();
            if("member".equals(user)){
                JOptionPane.showMessageDialog(this, "No tienes acceso a esta opción", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
        RegistroVotos.Registro r = new RegistroVotos.Registro();
        r.setVisible(true);
        this.dispose();
            }
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void BtnActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActaActionPerformed
        String user = Usuario.getRol();
            if("member".equals(user)){
                JOptionPane.showMessageDialog(this, "No tienes acceso a esta opción", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
        RegistroActaElectoral.ActaElectoral a = new RegistroActaElectoral.ActaElectoral();
        a.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_BtnActaActionPerformed

    private void BtnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVotarActionPerformed
        // TODO add your handling code here:
        InterfazVotacion.Votar v = new InterfazVotacion.Votar();
        v.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnVotarActionPerformed

    private void BtnConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConteoActionPerformed
        // TODO add your handling code here:
        String user = Usuario.getRol();
            if("member".equals(user)){
                JOptionPane.showMessageDialog(this, "No tienes acceso a esta opción", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
        Conteo a = new Conteo();
        a.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_BtnConteoActionPerformed

    private void BtnCerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerraActionPerformed
        // TODO add your handling code here:
        Iniciar i = new Iniciar();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCerraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActa;
    private javax.swing.JButton BtnCerra;
    private javax.swing.JButton BtnConteo;
    private javax.swing.JButton BtnEleccion;
    private javax.swing.JButton BtnMesa;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnVotar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
