package InicioMenuPrincipal;

import InicioMenuPrincipal.Usuario;
import InicioMenuPrincipal.Iniciar;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    static ArrayList<Usuario> listaUsuarios = new ArrayList<>();
    
    public Registrar() {
        initComponents();
    }
    
    public ArrayList<Usuario> getListaUsuarios() {
        return listaUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegistroUsuario = new javax.swing.JTextField();
        btnRegistroRegistrar = new javax.swing.JButton();
        txtRegistroContraseña = new javax.swing.JPasswordField();
        btnRegistroRegresar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRARSE");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        txtRegistroUsuario.setToolTipText("");
        txtRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroUsuario(evt);
            }
        });

        btnRegistroRegistrar.setText("Registrar");
        btnRegistroRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegitrarRegistrarse(evt);
            }
        });

        txtRegistroContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroContraseña(evt);
            }
        });

        btnRegistroRegresar.setText("Regresar");
        btnRegistroRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRegresar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtRegistroContraseña))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 114, Short.MAX_VALUE)
                .addComponent(btnRegistroRegresar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroRegistrar)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegistroContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroRegistrar)
                    .addComponent(btnRegistroRegresar))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistroUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroUsuario
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroUsuario

    private void btnRegitrarRegistrarse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegitrarRegistrarse
        // TODO add your handling code here:
        // Obtener el nombre de usuario y la contraseña de los campos de texto
        String nombreUsuario = txtRegistroUsuario.getText(); // Campo de texto para el nombre de usuario
        String contraseña = new String(txtRegistroContraseña.getPassword()); // Campo de contraseña
        String rol = "member";
        // Crear un nuevo objeto Usuario
        Usuario nuevoUsuario = new Usuario(nombreUsuario, contraseña, rol);

        // Añadir el nuevo usuario al ArrayList
        listaUsuarios.add(nuevoUsuario);

        // Mostrar un mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Usuario registrado", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos de texto después del registro
        txtRegistroUsuario.setText("");
        txtRegistroContraseña.setText("");
    }//GEN-LAST:event_btnRegitrarRegistrarse

    private void txtRegistroContraseña(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroContraseña
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroContraseña

    private void btnRegistrarRegresar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRegresar
        // TODO add your handling code here:// Crear una instancia de la pantalla principal
    Iniciar pantallaPrincipal = new Iniciar();
    
    // Hacer visible la pantalla principal
    pantallaPrincipal.setVisible(true);
    
    // Cerrar la ventana de registro actual
    this.dispose(); // Esto cierra la ventana actual (Registrar)
        
    }//GEN-LAST:event_btnRegistrarRegresar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroRegistrar;
    private javax.swing.JButton btnRegistroRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtRegistroContraseña;
    private javax.swing.JTextField txtRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
