package RegistroVotos;

import TDA.Cola;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import InicioMenuPrincipal.Menu;

/**
 *
 * @author Diego
 */
public class Registro extends javax.swing.JFrame {

    private int[] arr = new int[100]; // Array estático para almacenar hasta 100 valores
    private int contador = 0;
    DefaultTableModel mt = new DefaultTableModel();
    Cola colaVotos;

    public Registro() {
        initComponents();

        String ids[] = {"N° de mesa", "Total de votos"};
        mt.setColumnIdentifiers(ids);
        tblRegistro.setModel(mt);

        colaVotos = new Cola(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCalcular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtmesa = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE VOTOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Total de ciudadanos que votaron:");

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistro);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAction(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAction(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAction(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAction(evt);
            }
        });

        jLabel3.setText("N° de mesa");

        jLabel4.setText("Total de votos por mesa");

        BtnMenu.setText("Volver al menú");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(txtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(19, 19, 19)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BtnMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAction
// Obtener los datos de los campos de texto
    String nombreMesa = txtmesa.getText();
    String textoNumero = txtnumero.getText();

    // Verificar que los campos no estén vacíos
    if (nombreMesa.isEmpty() || textoNumero.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }

    // Convertir el texto del número total a entero
    int numerototal;
    try {
        numerototal = Integer.parseInt(textoNumero);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.");
        return;
    }

    // Verificar que el número total esté dentro de los límites de un char
//    if (numerototal < 0 || numerototal > 255) {
//        JOptionPane.showMessageDialog(this, "El número total debe estar entre 0 y 255.");
//        return;
//    }

    // Crear la cadena concatenada para la columna "N° de mesa"
    String mesaConcatenada = "Mesa " + nombreMesa;

    // Encolar los votos como char
    colaVotos.enqueue((char) numerototal);

    // Agregar el número total al array en la posición actual del contador
    arr[contador] = numerototal;
    contador++; // Incrementa el contador para la siguiente posición del array

    // Agregar directamente la fila a la tabla
    mt.addRow(new Object[]{mesaConcatenada, numerototal});

    // Limpiar los campos de texto
    txtmesa.setText("");
    txtnumero.setText("");

    JOptionPane.showMessageDialog(this, "Datos agregados correctamente.");

    }//GEN-LAST:event_btnAgregarAction

    private void btnModificarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAction
        // Verifica que haya una fila seleccionada
    int selectedIndex = tblRegistro.getSelectedRow();
    if (selectedIndex >= 0) {
        // Verifica que los campos de texto no estén vacíos
        String mesaEditada = txtmesa.getText().trim();
        String textoNumero = txtnumero.getText().trim();

        if (mesaEditada.isEmpty() || textoNumero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa ambos campos.");
            return;
        }

        // Intenta convertir el número ingresado a un entero
        int numeroEditado;
        try {
            numeroEditado = Integer.parseInt(textoNumero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.");
            return;
        }

        // Verifica que el número total esté dentro del rango de un char
//        if (numeroEditado < 0 || numeroEditado > 255) {
//            JOptionPane.showMessageDialog(this, "El número total debe estar entre 0 y 255.");
//            return;
//        }

        // Actualiza los valores en la tabla
        String mesaConcatenada = "Mesa " + mesaEditada;
        mt.setValueAt(mesaConcatenada, selectedIndex, 0); // Actualiza la columna de "N° de mesa"
        mt.setValueAt(numeroEditado, selectedIndex, 1);   // Actualiza la columna de "Total de votos"

        // Actualiza el valor correspondiente en el array
        arr[selectedIndex] = numeroEditado;

        // Limpia los campos de texto después de modificar
        txtmesa.setText("");
        txtnumero.setText("");

        // Mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Mesa modificada correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para modificar.");
    }
    }//GEN-LAST:event_btnModificarAction


    private void btnEliminarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAction
        // Verificar si hay una fila seleccionada antes de eliminarla
        int selectedIndex = tblRegistro.getSelectedRow();
        if (selectedIndex >= 0) {
            // Eliminar la fila de la tabla
            mt.removeRow(selectedIndex);

            // Desplazar los elementos en el array después de la eliminación
            for (int i = selectedIndex; i < contador - 1; i++) {
                arr[i] = arr[i + 1];
            }
            arr[contador - 1] = 0; // Limpiar la última posición del array
            contador--; // Reducir el contador
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarAction

    private void btnCalcularAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAction
        // Inicializar una variable para sumar los votos
        int sumaTotal = 0;

        // Iterar sobre el array para sumar los votos almacenados
        for (int i = 0; i < contador; i++) {
            sumaTotal += arr[i];
        }

        // Mostrar el resultado en el campo de texto txtCalcular
        txtCalcular.setText(String.valueOf(sumaTotal));
    }//GEN-LAST:event_btnCalcularAction

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistro;
    private javax.swing.JTextField txtCalcular;
    private javax.swing.JTextField txtmesa;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
