package GestionCandidatos;

import RegistroActaElectoral.ActaElectoral;
import javax.swing.JOptionPane;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import InicioMenuPrincipal.Menu;
import mesaElectoral.MesaVotacion;


public class JframeRegional extends javax.swing.JFrame {

    private ColaGenerica colaRegional;
    private DefaultTableModel modelo;

    private Regional[] regionales = new Regional[50]; // Usamos un array fijo de tamaño 50
    private int contadorRegionales = 0; // Contador para saber cuántos regionales hay
    private ActaElectoral actaElectoral;
    private GestionRegional gestion3 = new GestionRegional(); // Cambiado a GestionRegional

    /**
     * Creates new form JframeRegional
     */
    public JframeRegional() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Las celdas no son editables
            }
        };

        colaRegional = new ColaGenerica(50); // Tamaño de la cola
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Partido Político");
        tblRegional.setModel(modelo);

        cargarRegionales(); // Carga los regionales al iniciar
        actaElectoral = new ActaElectoral();
        setTitle("Elección Regional");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Las celdas no son editables
            }
        };

        colaRegional = new ColaGenerica(50); // Tamaño de la cola
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Partido Político");
        tblRegional.setModel(modelo);

        cargarRegionales(); // Carga los regionales al iniciar

    }

// Sobreescribe setVisible para recargar los datos cada vez que se muestra la ventana
    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            cargarRegionales();
        }
        super.setVisible(visible);
    }

    private void cargarRegionales() {
        for (int i = 0; i < contadorRegionales; i++) {
            Regional regional = regionales[i]; // Cambiado de municipal a regional
            String[] fila = {regional.getDni(), regional.getNombre(), regional.getApellido(), regional.getPartidoPolitico()};
            modelo.addRow(fila); // Agrega la fila de datos a la tabla
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegional = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreRegional = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoRegional = new javax.swing.JTextField();
        txtPartidoPoliticoRegional = new javax.swing.JTextField();
        btnAgregarRegional = new javax.swing.JButton();
        btnModificarRegional = new javax.swing.JButton();
        btnEliminarRegional = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDniRegional = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("GESTION DE DATOS REGIONALES");

        tblRegional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegional);

        jLabel4.setText("Partido politico:");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        btnAgregarRegional.setText("Agregar");
        btnAgregarRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegional(evt);
            }
        });

        btnModificarRegional.setText("Modificar");
        btnModificarRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRegional(evt);
            }
        });

        btnEliminarRegional.setText("Eliminar");
        btnEliminarRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegional(evt);
            }
        });

        jLabel3.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoRegional)
                            .addComponent(txtNombreRegional)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregarRegional)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnModificarRegional)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminarRegional)
                                        .addGap(0, 16, Short.MAX_VALUE))
                                    .addComponent(txtPartidoPoliticoRegional)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDniRegional)))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDniRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPartidoPoliticoRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRegional)
                    .addComponent(btnModificarRegional)
                    .addComponent(btnEliminarRegional))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton2.setText("Crear o iniciar mesa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnMenu.setText("Volver al menú");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BtnMenu))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRegional(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegional
        String dni = txtDniRegional.getText();
    String nombre = txtNombreRegional.getText();
    String apellido = txtApellidoRegional.getText();
    String partido = txtPartidoPoliticoRegional.getText();

    // Crear un objeto Regional con los datos ingresados
    Regional regional = new Regional(dni, nombre, apellido, partido);

    // Si se está modificando (cuando ya existe el DNI), actualiza
    int selectedIndex = this.tblRegional.getSelectedRow();
    if (selectedIndex >= 0) {  // Si hay una fila seleccionada
        // Actualizar el regional en la lista de gestión
//        gestion3.cargarRegionales(regional);  // Suponiendo que hay un método para actualizar

        // Actualiza la fila en la tabla con los nuevos datos
        modelo.setValueAt(dni, selectedIndex, 0);
        modelo.setValueAt(nombre, selectedIndex, 1);
        modelo.setValueAt(apellido, selectedIndex, 2);
        modelo.setValueAt(partido, selectedIndex, 3);
    } else {
        // Si no hay fila seleccionada, agregamos uno nuevo
        gestion3.insertar(regional);
        colaRegional.agregar(regional);
        RegistroCandidatos.getInstance().agregarCandidato(nombre + " " + apellido + " | " + partido);

        // Agregar el nuevo regional a la tabla
        modelo.addRow(new Object[]{dni, nombre, apellido, partido});
    }

    // Limpiar los campos después de agregar o modificar
    limpiarCampos();
    }//GEN-LAST:event_btnAgregarRegional

//    private int selectedMemberIndex = -1;

    private void btnModificarRegional(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRegional
        // Obtiene el índice de la fila seleccionada en la tabla
    int selectedIndex = this.tblRegional.getSelectedRow();

    if (selectedIndex >= 0) {  // Verifica que se haya seleccionado una fila
        // Obtiene los datos de la fila seleccionada
        String dniRegional = modelo.getValueAt(selectedIndex, 0).toString();
        String nombreRegional = modelo.getValueAt(selectedIndex, 1).toString();
        String apellidoRegional = modelo.getValueAt(selectedIndex, 2).toString();
        String partidoRegional = modelo.getValueAt(selectedIndex, 3).toString();

        // Muestra los datos en los campos de texto
        txtDniRegional.setText(dniRegional);
        txtNombreRegional.setText(nombreRegional);
        txtApellidoRegional.setText(apellidoRegional);
        txtPartidoPoliticoRegional.setText(partidoRegional);
    }

    }//GEN-LAST:event_btnModificarRegional

    private void limpiarCampos() {
        this.txtDniRegional.setText(""); // Limpia el campo de DNI de regional
        this.txtNombreRegional.setText(""); // Limpia el campo de nombre de regional
        this.txtApellidoRegional.setText(""); // Limpia el campo de apellido de regional
        this.txtPartidoPoliticoRegional.setText(""); // Limpia el campo de partido político de regional
        cargarRegionales(); // Recarga los regionales en la tabla
    }

    private void btnEliminarRegional(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegional
        int filaSeleccionada = tblRegional.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String dni = modelo.getValueAt(filaSeleccionada, 0).toString();
            gestion3.eliminar(dni); // Elimina de la lista enlazada de regionales
            modelo.removeRow(filaSeleccionada); // Elimina de la tabla
        }

    }//GEN-LAST:event_btnEliminarRegional

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Mostrar un mensaje de confirmación antes de continuar
    int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

    // Si el usuario selecciona "Sí" (respuesta == JOptionPane.YES_OPTION)
    if (respuesta == JOptionPane.YES_OPTION) {
        // Crear una instancia de la nueva ventana (VentanaSecundaria)
        MesaVotacion ventana = new MesaVotacion();

        // Hacer visible la nueva ventana
        ventana.setVisible(true);

        // Cerrar la ventana actual (opcional)
        this.dispose();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

//    public ArrayList<String> obtenerNombresConPartido() {
//        ArrayList<String> nombresConPartido = new ArrayList<>();
//        for (int i = 0; i < modelo.getRowCount(); i++) {
//            String nombre = modelo.getValueAt(i, 1).toString();
//            String apellido = modelo.getValueAt(i, 2).toString();
//            String partidoPolitico = modelo.getValueAt(i, 3).toString();
//
//            String item = nombre + " " + apellido + " | " + partidoPolitico;
//            nombresConPartido.add(item);
//        }
//        return nombresConPartido;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeRegional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeRegional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeRegional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeRegional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeRegional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton btnAgregarRegional;
    private javax.swing.JButton btnEliminarRegional;
    private javax.swing.JButton btnModificarRegional;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegional;
    private javax.swing.JTextField txtApellidoRegional;
    private javax.swing.JTextField txtDniRegional;
    private javax.swing.JTextField txtNombreRegional;
    private javax.swing.JTextField txtPartidoPoliticoRegional;
    // End of variables declaration//GEN-END:variables
}
