package InicioPantallaVotacion;

import TDA.ListaEnlazada;
import TDA.Nodo;
import TDA.Pila;
import RegistroActaElectoral.ActaElectoral;
import javax.swing.JOptionPane;
import InicioMenuPrincipal.Menu;
import InterfazVotacion.Votar;

public class InicioVotante extends javax.swing.JFrame {

    private ListaEnlazada<Persona> listaUsuarios = Registrar.listaUsuarios; // Obtenemos la lista de usuarios desde Registrar
    private Pila pilaIntentos = new Pila(5);  // Usamos la pila de intentos de inicio de sesión

    public InicioVotante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_sis_label = new javax.swing.JLabel();
        contrase_label = new javax.swing.JLabel();
        usuario_label = new javax.swing.JLabel();
        usuario_TextField = new javax.swing.JTextField();
        iniciar_sesion_Button = new javax.swing.JButton();
        contrase_PasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo_sis_label.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        titulo_sis_label.setText("Iniciar votacion");
        titulo_sis_label.setToolTipText("");

        contrase_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        contrase_label.setText("Contraseña:");

        usuario_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usuario_label.setText("Usuario:");

        usuario_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrincipalUsuario(evt);
            }
        });

        iniciar_sesion_Button.setText("Iniciar sesion");
        iniciar_sesion_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar(evt);
            }
        });

        contrase_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrincipalContraseña(evt);
            }
        });

        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrarse_BTN(evt);
            }
        });

        BtnMenu.setText("Volver al menú");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuario_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(usuario_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contrase_label)
                                .addGap(18, 18, 18)
                                .addComponent(contrase_PasswordField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(iniciar_sesion_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(titulo_sis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(BtnMenu)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnMenu)
                .addGap(9, 9, 9)
                .addComponent(titulo_sis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrase_label)
                    .addComponent(contrase_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar_sesion_Button)
                    .addComponent(jButton1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrincipalUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrincipalUsuario
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrincipalUsuario

    private void btnIniciar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar
        String usuario = usuario_TextField.getText();
        String password = new String(contrase_PasswordField.getPassword());

        // Verificar credenciales de admin
        if (usuario.equals("user") && password.equals("123")) {
            Votar eleccion = new Votar(); // Crear instancia de la nueva ventana
            eleccion.setVisible(true); // Mostrar la nueva ventana
            this.dispose();
        } else {
            // Verificar en la lista de usuarios registrados
            boolean loginExitoso = false;

            // Buscar el usuario en la lista enlazada
            Nodo<Persona> currentNode = listaUsuarios.GetFirst();
            while (currentNode != null) {
                Persona u = currentNode.getValue();
                if (u.getNombreUsuario().equals(usuario) && u.getContraseña().equals(password)) {
                    loginExitoso = true;
                    break; // Si se encuentra, salir del bucle
                }
                currentNode = currentNode.getNext();
            }

            // Si se encuentra el usuario, se permite el acceso
            if (loginExitoso) {
                Votar eleccion = new Votar(); // Crear instancia de la nueva ventana
                eleccion.setVisible(true); // Mostrar la nueva ventana
                this.dispose(); // Cerrar la ventana actual

                // Registrar el intento de inicio de sesión exitoso en la pila
                pilaIntentos.push('S');  // 'S' para inicio exitoso
            } else {
                JOptionPane.showMessageDialog(this, "Error de usuario o contraseña", "Error", JOptionPane.ERROR_MESSAGE);

                // Registrar el intento fallido en la pila
                pilaIntentos.push('F');  // 'F' para inicio fallido
            }
        }

    }//GEN-LAST:event_btnIniciar

    private void Registrarse_BTN(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrarse_BTN
        // TODO add your handling code here:
        // Crear una instancia de la nueva ventana (VentanaSecundaria)
        Registrar ventana = new Registrar();

        // Hacer visible la nueva ventana
        ventana.setVisible(true);

        // Cerrar la ventana actual (opcional)
        this.dispose();
    }//GEN-LAST:event_Registrarse_BTN

    private void txtPrincipalContraseña(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrincipalContraseña
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrincipalContraseña

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioVotante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JPasswordField contrase_PasswordField;
    private javax.swing.JLabel contrase_label;
    private javax.swing.JButton iniciar_sesion_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel titulo_sis_label;
    private javax.swing.JTextField usuario_TextField;
    private javax.swing.JLabel usuario_label;
    // End of variables declaration//GEN-END:variables
}
